
# 포트 번호 변경
server:
  port: 9090
  servlet:
    encoding:
      charset: UTF-8

# 디버그 콘솔 색 넣기
spring:
  output:
    ansi:
      enabled: always

# 디버그 레벨 정하기
logging:
  level:
    '[com.jjang051.ch02]': DEBUG # ERROR로 바꾸면 ERROR 관련 사항만 뜬다

